# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Get the box
  config.vm.box     = "chef/fedora-20"
  config.vm.box_url = "https://vagrantcloud.com/chef/fedora-20/version/1/provider/virtualbox.box"

  # If true, Vagrant will check for updates to the configured box on every vagrant up.
  # If an update is found, Vagrant will tell the user.
  config.vm.box_check_update = true

  # The checksum of the box specified by config.vm.box_url.  if not specified
  # no checksum comparison will be done.  If specified, Vagrant will compare the
  # checksum of the downloaded box to this value and error if they do not match.
  # Checksum checking is only done when Vagrant must download the box.
  config.vm.box_download_checksum      = true
  config.vm.box_download_checksum_type = 'sha1'

  # Mount some directories from the host machine
  config.vm.synced_folder "/home/sean.humbarger/workspace", "/workspace"

  # Configuration Script
  config.vm.provision "shell", path: "configure", privileged: true

  # the time in seconds that Vagrant will wait for the machine to boot and be accessible
  config.vm.boot_timeout = 300

  # Path to a client cert to use when downloading the box, if it is
  # necessary. By default, no client cert is used to download the box
  # config.vm.box_download_client_cert

  # If true, then SSL certificates from the server will not be verified.  By default,
  # if the URL is an HTTPS URL, then SSL certs will be verified.
  # What is the validation done against?
  config.vm.box_download_insecure = true

  # Configuration SSH
  config.ssh.forward_agent = true
  config.ssh.forward_x11   = true

  # The time in seconds that Vagrant will wait for the machine
  # to gracefullyhalt when 'vagrant halt' is called.  Defaults to 60
  config.vm.graceful_halt_timeout = 60

  # The guest OS that will be running within this machine.
  config.vm.guest = :linux

  # The hostname the machine should have.
  #config.vm.hostname = "dev-env"

  # Range ofports Vagrant can use for handling port collisions
  config.vm.usable_port_range = 2200..2250

  # Configures teh network on the machine
  # config.vm.network

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Name of the VM
    vb.name = "dev-env"

    # Boot Headless (not really sure how vagrant does this)
    vb.gui = false

    # Set memory and CPUs
    vb.memory = 2048
    vb.cpus   = 2

    # No matter how much CPU is used on the VM, no more than 50% would be used on your host
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
